# **********************************************************************
#
# Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.4.2
#
# <auto-generated>
#
# Generated from file `Scanner.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy, __builtin__
import omero_model_IObject_ice
import omero_RTypes_ice
import omero_System_ice
import omero_Collections_ice
import omero_model_HardwareDevice_ice

# Included module omero
_M_omero = Ice.openModule('omero')

# Included module omero.model
_M_omero.model = Ice.openModule('omero.model')

# Included module Ice
_M_Ice = Ice.openModule('Ice')

# Included module omero.sys
_M_omero.sys = Ice.openModule('omero.sys')

# Included module omero.api
_M_omero.api = Ice.openModule('omero.api')

# Start of module omero
__name__ = 'omero'

# Start of module omero.model
__name__ = 'omero.model'

if not _M_omero.model.__dict__.has_key('Details'):
    _M_omero.model._t_Details = IcePy.declareClass('::omero::model::Details')
    _M_omero.model._t_DetailsPrx = IcePy.declareProxy('::omero::model::Details')

if not _M_omero.model.__dict__.has_key('Scanner'):
    _M_omero.model.Scanner = Ice.createTempClass()
    class Scanner(_M_omero.model.HardwareDevice):
        def __init__(self, _id=None, _details=None, _loaded=False, _version=None, _vid=None, _label=None, _maker=None, _model=None, _release=None, _barcode=None, _physicalLocation=None):
            if __builtin__.type(self) == _M_omero.model.Scanner:
                raise RuntimeError('omero.model.Scanner is an abstract class')
            _M_omero.model.HardwareDevice.__init__(self, _id, _details, _loaded, _version, _vid, _label, _maker, _model, _release, _barcode, _physicalLocation)

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::omero::model::Device', '::omero::model::HardwareDevice', '::omero::model::IObject', '::omero::model::Scanner')

        def ice_id(self, current=None):
            return '::omero::model::Scanner'

        def ice_staticId():
            return '::omero::model::Scanner'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_omero.model._t_Scanner)

        __repr__ = __str__

    _M_omero.model.ScannerPrx = Ice.createTempClass()
    class ScannerPrx(_M_omero.model.HardwareDevicePrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_omero.model.ScannerPrx.ice_checkedCast(proxy, '::omero::model::Scanner', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_omero.model.ScannerPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_omero.model._t_ScannerPrx = IcePy.defineProxy('::omero::model::Scanner', ScannerPrx)

    _M_omero.model._t_Scanner = IcePy.declareClass('::omero::model::Scanner')

    _M_omero.model._t_Scanner = IcePy.defineClass('::omero::model::Scanner', Scanner, (), True, _M_omero.model._t_HardwareDevice, (), ())
    Scanner._ice_type = _M_omero.model._t_Scanner

    _M_omero.model.Scanner = Scanner
    del Scanner

    _M_omero.model.ScannerPrx = ScannerPrx
    del ScannerPrx

# End of module omero.model

__name__ = 'omero'

# End of module omero
