# **********************************************************************
#
# Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.4.2
#
# <auto-generated>
#
# Generated from file `VLCollection.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy, __builtin__
import omero_model_IObject_ice
import omero_RTypes_ice
import omero_System_ice
import omero_Collections_ice

# Included module omero
_M_omero = Ice.openModule('omero')

# Included module omero.model
_M_omero.model = Ice.openModule('omero.model')

# Included module Ice
_M_Ice = Ice.openModule('Ice')

# Included module omero.sys
_M_omero.sys = Ice.openModule('omero.sys')

# Included module omero.api
_M_omero.api = Ice.openModule('omero.api')

# Start of module omero
__name__ = 'omero'

# Start of module omero.model
__name__ = 'omero.model'

if not _M_omero.model.__dict__.has_key('Action'):
    _M_omero.model._t_Action = IcePy.declareClass('::omero::model::Action')
    _M_omero.model._t_ActionPrx = IcePy.declareProxy('::omero::model::Action')

if not _M_omero.model.__dict__.has_key('Details'):
    _M_omero.model._t_Details = IcePy.declareClass('::omero::model::Details')
    _M_omero.model._t_DetailsPrx = IcePy.declareProxy('::omero::model::Details')

if not _M_omero.model.__dict__.has_key('VLCollection'):
    _M_omero.model.VLCollection = Ice.createTempClass()
    class VLCollection(_M_omero.model.IObject):
        def __init__(self, _id=None, _details=None, _loaded=False, _version=None, _vid=None, _label=None, _creationDate=None, _action=None, _lastUpdate=None):
            if __builtin__.type(self) == _M_omero.model.VLCollection:
                raise RuntimeError('omero.model.VLCollection is an abstract class')
            _M_omero.model.IObject.__init__(self, _id, _details, _loaded)
            self._version = _version
            self._vid = _vid
            self._label = _label
            self._creationDate = _creationDate
            self._action = _action
            self._lastUpdate = _lastUpdate

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::omero::model::IObject', '::omero::model::VLCollection')

        def ice_id(self, current=None):
            return '::omero::model::VLCollection'

        def ice_staticId():
            return '::omero::model::VLCollection'
        ice_staticId = staticmethod(ice_staticId)

        def getVersion(self, current=None):
            pass

        def setVersion(self, theVersion, current=None):
            pass

        def getVid(self, current=None):
            pass

        def setVid(self, theVid, current=None):
            pass

        def getLabel(self, current=None):
            pass

        def setLabel(self, theLabel, current=None):
            pass

        def getCreationDate(self, current=None):
            pass

        def setCreationDate(self, theCreationDate, current=None):
            pass

        def getAction(self, current=None):
            pass

        def setAction(self, theAction, current=None):
            pass

        def getLastUpdate(self, current=None):
            pass

        def setLastUpdate(self, theLastUpdate, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_omero.model._t_VLCollection)

        __repr__ = __str__

    _M_omero.model.VLCollectionPrx = Ice.createTempClass()
    class VLCollectionPrx(_M_omero.model.IObjectPrx):

        def getVersion(self, _ctx=None):
            return _M_omero.model.VLCollection._op_getVersion.invoke(self, ((), _ctx))

        def begin_getVersion(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_getVersion.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getVersion(self, _r):
            return _M_omero.model.VLCollection._op_getVersion.end(self, _r)

        def setVersion(self, theVersion, _ctx=None):
            return _M_omero.model.VLCollection._op_setVersion.invoke(self, ((theVersion, ), _ctx))

        def begin_setVersion(self, theVersion, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_setVersion.begin(self, ((theVersion, ), _response, _ex, _sent, _ctx))

        def end_setVersion(self, _r):
            return _M_omero.model.VLCollection._op_setVersion.end(self, _r)

        def getVid(self, _ctx=None):
            return _M_omero.model.VLCollection._op_getVid.invoke(self, ((), _ctx))

        def begin_getVid(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_getVid.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getVid(self, _r):
            return _M_omero.model.VLCollection._op_getVid.end(self, _r)

        def setVid(self, theVid, _ctx=None):
            return _M_omero.model.VLCollection._op_setVid.invoke(self, ((theVid, ), _ctx))

        def begin_setVid(self, theVid, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_setVid.begin(self, ((theVid, ), _response, _ex, _sent, _ctx))

        def end_setVid(self, _r):
            return _M_omero.model.VLCollection._op_setVid.end(self, _r)

        def getLabel(self, _ctx=None):
            return _M_omero.model.VLCollection._op_getLabel.invoke(self, ((), _ctx))

        def begin_getLabel(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_getLabel.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getLabel(self, _r):
            return _M_omero.model.VLCollection._op_getLabel.end(self, _r)

        def setLabel(self, theLabel, _ctx=None):
            return _M_omero.model.VLCollection._op_setLabel.invoke(self, ((theLabel, ), _ctx))

        def begin_setLabel(self, theLabel, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_setLabel.begin(self, ((theLabel, ), _response, _ex, _sent, _ctx))

        def end_setLabel(self, _r):
            return _M_omero.model.VLCollection._op_setLabel.end(self, _r)

        def getCreationDate(self, _ctx=None):
            return _M_omero.model.VLCollection._op_getCreationDate.invoke(self, ((), _ctx))

        def begin_getCreationDate(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_getCreationDate.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getCreationDate(self, _r):
            return _M_omero.model.VLCollection._op_getCreationDate.end(self, _r)

        def setCreationDate(self, theCreationDate, _ctx=None):
            return _M_omero.model.VLCollection._op_setCreationDate.invoke(self, ((theCreationDate, ), _ctx))

        def begin_setCreationDate(self, theCreationDate, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_setCreationDate.begin(self, ((theCreationDate, ), _response, _ex, _sent, _ctx))

        def end_setCreationDate(self, _r):
            return _M_omero.model.VLCollection._op_setCreationDate.end(self, _r)

        def getAction(self, _ctx=None):
            return _M_omero.model.VLCollection._op_getAction.invoke(self, ((), _ctx))

        def begin_getAction(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_getAction.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getAction(self, _r):
            return _M_omero.model.VLCollection._op_getAction.end(self, _r)

        def setAction(self, theAction, _ctx=None):
            return _M_omero.model.VLCollection._op_setAction.invoke(self, ((theAction, ), _ctx))

        def begin_setAction(self, theAction, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_setAction.begin(self, ((theAction, ), _response, _ex, _sent, _ctx))

        def end_setAction(self, _r):
            return _M_omero.model.VLCollection._op_setAction.end(self, _r)

        def getLastUpdate(self, _ctx=None):
            return _M_omero.model.VLCollection._op_getLastUpdate.invoke(self, ((), _ctx))

        def begin_getLastUpdate(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_getLastUpdate.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getLastUpdate(self, _r):
            return _M_omero.model.VLCollection._op_getLastUpdate.end(self, _r)

        def setLastUpdate(self, theLastUpdate, _ctx=None):
            return _M_omero.model.VLCollection._op_setLastUpdate.invoke(self, ((theLastUpdate, ), _ctx))

        def begin_setLastUpdate(self, theLastUpdate, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.VLCollection._op_setLastUpdate.begin(self, ((theLastUpdate, ), _response, _ex, _sent, _ctx))

        def end_setLastUpdate(self, _r):
            return _M_omero.model.VLCollection._op_setLastUpdate.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_omero.model.VLCollectionPrx.ice_checkedCast(proxy, '::omero::model::VLCollection', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_omero.model.VLCollectionPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_omero.model._t_VLCollectionPrx = IcePy.defineProxy('::omero::model::VLCollection', VLCollectionPrx)

    _M_omero.model._t_VLCollection = IcePy.declareClass('::omero::model::VLCollection')

    _M_omero.model._t_VLCollection = IcePy.defineClass('::omero::model::VLCollection', VLCollection, (), True, _M_omero.model._t_IObject, (), (
        ('_version', (), _M_omero._t_RInt),
        ('_vid', (), _M_omero._t_RString),
        ('_label', (), _M_omero._t_RString),
        ('_creationDate', (), _M_omero._t_RTime),
        ('_action', (), _M_omero.model._t_Action),
        ('_lastUpdate', (), _M_omero.model._t_Action)
    ))
    VLCollection._ice_type = _M_omero.model._t_VLCollection

    VLCollection._op_getVersion = IcePy.Operation('getVersion', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), _M_omero._t_RInt, ())
    VLCollection._op_setVersion = IcePy.Operation('setVersion', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), _M_omero._t_RInt),), (), None, ())
    VLCollection._op_getVid = IcePy.Operation('getVid', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), _M_omero._t_RString, ())
    VLCollection._op_setVid = IcePy.Operation('setVid', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), _M_omero._t_RString),), (), None, ())
    VLCollection._op_getLabel = IcePy.Operation('getLabel', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), _M_omero._t_RString, ())
    VLCollection._op_setLabel = IcePy.Operation('setLabel', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), _M_omero._t_RString),), (), None, ())
    VLCollection._op_getCreationDate = IcePy.Operation('getCreationDate', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), _M_omero._t_RTime, ())
    VLCollection._op_setCreationDate = IcePy.Operation('setCreationDate', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), _M_omero._t_RTime),), (), None, ())
    VLCollection._op_getAction = IcePy.Operation('getAction', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), _M_omero.model._t_Action, ())
    VLCollection._op_setAction = IcePy.Operation('setAction', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), _M_omero.model._t_Action),), (), None, ())
    VLCollection._op_getLastUpdate = IcePy.Operation('getLastUpdate', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), _M_omero.model._t_Action, ())
    VLCollection._op_setLastUpdate = IcePy.Operation('setLastUpdate', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), _M_omero.model._t_Action),), (), None, ())

    _M_omero.model.VLCollection = VLCollection
    del VLCollection

    _M_omero.model.VLCollectionPrx = VLCollectionPrx
    del VLCollectionPrx

# End of module omero.model

__name__ = 'omero'

# End of module omero
