# **********************************************************************
#
# Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.4.2
#
# <auto-generated>
#
# Generated from file `SeqDataSample.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy, __builtin__
import omero_model_IObject_ice
import omero_RTypes_ice
import omero_System_ice
import omero_Collections_ice
import omero_model_DataSample_ice

# Included module omero
_M_omero = Ice.openModule('omero')

# Included module omero.model
_M_omero.model = Ice.openModule('omero.model')

# Included module Ice
_M_Ice = Ice.openModule('Ice')

# Included module omero.sys
_M_omero.sys = Ice.openModule('omero.sys')

# Included module omero.api
_M_omero.api = Ice.openModule('omero.api')

# Start of module omero
__name__ = 'omero'

# Start of module omero.model
__name__ = 'omero.model'

if not _M_omero.model.__dict__.has_key('Tube'):
    _M_omero.model._t_Tube = IcePy.declareClass('::omero::model::Tube')
    _M_omero.model._t_TubePrx = IcePy.declareProxy('::omero::model::Tube')

if not _M_omero.model.__dict__.has_key('DataSampleStatus'):
    _M_omero.model._t_DataSampleStatus = IcePy.declareClass('::omero::model::DataSampleStatus')
    _M_omero.model._t_DataSampleStatusPrx = IcePy.declareProxy('::omero::model::DataSampleStatus')

if not _M_omero.model.__dict__.has_key('Action'):
    _M_omero.model._t_Action = IcePy.declareClass('::omero::model::Action')
    _M_omero.model._t_ActionPrx = IcePy.declareProxy('::omero::model::Action')

if not _M_omero.model.__dict__.has_key('Details'):
    _M_omero.model._t_Details = IcePy.declareClass('::omero::model::Details')
    _M_omero.model._t_DetailsPrx = IcePy.declareProxy('::omero::model::Details')

if not _M_omero.model.__dict__.has_key('SeqDataSample'):
    _M_omero.model.SeqDataSample = Ice.createTempClass()
    class SeqDataSample(_M_omero.model.DataSample):
        def __init__(self, _id=None, _details=None, _loaded=False, _version=None, _vid=None, _label=None, _creationDate=None, _status=None, _action=None, _sample=None):
            if __builtin__.type(self) == _M_omero.model.SeqDataSample:
                raise RuntimeError('omero.model.SeqDataSample is an abstract class')
            _M_omero.model.DataSample.__init__(self, _id, _details, _loaded, _version, _vid, _label, _creationDate, _status, _action)
            self._sample = _sample

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::omero::model::DataSample', '::omero::model::IObject', '::omero::model::SeqDataSample')

        def ice_id(self, current=None):
            return '::omero::model::SeqDataSample'

        def ice_staticId():
            return '::omero::model::SeqDataSample'
        ice_staticId = staticmethod(ice_staticId)

        def getSample(self, current=None):
            pass

        def setSample(self, theSample, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_omero.model._t_SeqDataSample)

        __repr__ = __str__

    _M_omero.model.SeqDataSamplePrx = Ice.createTempClass()
    class SeqDataSamplePrx(_M_omero.model.DataSamplePrx):

        def getSample(self, _ctx=None):
            return _M_omero.model.SeqDataSample._op_getSample.invoke(self, ((), _ctx))

        def begin_getSample(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.SeqDataSample._op_getSample.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getSample(self, _r):
            return _M_omero.model.SeqDataSample._op_getSample.end(self, _r)

        def setSample(self, theSample, _ctx=None):
            return _M_omero.model.SeqDataSample._op_setSample.invoke(self, ((theSample, ), _ctx))

        def begin_setSample(self, theSample, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.SeqDataSample._op_setSample.begin(self, ((theSample, ), _response, _ex, _sent, _ctx))

        def end_setSample(self, _r):
            return _M_omero.model.SeqDataSample._op_setSample.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_omero.model.SeqDataSamplePrx.ice_checkedCast(proxy, '::omero::model::SeqDataSample', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_omero.model.SeqDataSamplePrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_omero.model._t_SeqDataSamplePrx = IcePy.defineProxy('::omero::model::SeqDataSample', SeqDataSamplePrx)

    _M_omero.model._t_SeqDataSample = IcePy.declareClass('::omero::model::SeqDataSample')

    _M_omero.model._t_SeqDataSample = IcePy.defineClass('::omero::model::SeqDataSample', SeqDataSample, (), True, _M_omero.model._t_DataSample, (), (('_sample', (), _M_omero.model._t_Tube),))
    SeqDataSample._ice_type = _M_omero.model._t_SeqDataSample

    SeqDataSample._op_getSample = IcePy.Operation('getSample', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), _M_omero.model._t_Tube, ())
    SeqDataSample._op_setSample = IcePy.Operation('setSample', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), _M_omero.model._t_Tube),), (), None, ())

    _M_omero.model.SeqDataSample = SeqDataSample
    del SeqDataSample

    _M_omero.model.SeqDataSamplePrx = SeqDataSamplePrx
    del SeqDataSamplePrx

# End of module omero.model

__name__ = 'omero'

# End of module omero
