"""
   /*
   **   Generated by blitz/templates/resouces/combined.vm
   **
   **   Copyright 2007, 2008 Glencoe Software, Inc. All rights reserved.
   **   Use is subject to license terms supplied in LICENSE.txt
   **
   */
"""
import Ice
import IceImport
import omero
IceImport.load("omero_model_DetailsI")
IceImport.load("omero_model_Individual_ice")
from omero.rtypes import rlong
_omero = Ice.openModule("omero")
_omero_model = Ice.openModule("omero.model")
__name__ = "omero.model"
class IndividualI(_omero_model.Individual):

      VID =  "ome.model.vl.Individual_vid"
      GENDER =  "ome.model.vl.Individual_gender"
      FATHER =  "ome.model.vl.Individual_father"
      FATHERTRUSTED =  "ome.model.vl.Individual_fatherTrusted"
      MOTHER =  "ome.model.vl.Individual_mother"
      MOTHERTRUSTED =  "ome.model.vl.Individual_motherTrusted"
      ACTION =  "ome.model.vl.Individual_action"
      LASTUPDATE =  "ome.model.vl.Individual_lastUpdate"
      DETAILS =  "ome.model.vl.Individual_details"
      def errorIfUnloaded(self):
          if not self._loaded:
              raise _omero.UnloadedEntityException("Object unloaded:"+str(self))

      def throwNullCollectionException(self,propertyName):
          raise _omero.UnloadedEntityException(""+
          "Error updating collection:" + propertyName +"\n"+
          "Collection is currently null. This can be seen\n" +
          "by testing \""+ propertyName +"Loaded\". This implies\n"+
          "that this collection was unloaded. Please refresh this object\n"+
          "in order to update this collection.\n")

      def _toggleCollectionsLoaded(self,load):
          pass

      def __init__(self, id = None, loaded = True):
          super(IndividualI, self).__init__()
          # Relying on omero.rtypes.rlong's error-handling
          self._id = rlong(id)
          self._loaded = loaded
          if self._loaded:
             self._details = _omero_model.DetailsI()
             self._toggleCollectionsLoaded(True)

      def unload(self, current = None):
          self._loaded = False
          self.unloadVid( )
          self.unloadGender( )
          self.unloadFather( )
          self.unloadFatherTrusted( )
          self.unloadMother( )
          self.unloadMotherTrusted( )
          self.unloadAction( )
          self.unloadLastUpdate( )
          self.unloadDetails( )

      def isLoaded(self, current = None):
          return self._loaded
      def unloadCollections(self, current = None):
          self._toggleCollectionsLoaded( False )
      def isGlobal(self, current = None):
          return  False ;
      def isMutable(self, current = None):
          return  True ;
      def isAnnotated(self, current = None):
          return  False ;
      def isLink(self, current = None):
          return  False ;
      def shallowCopy(self, current = None):
            if not self._loaded: return self.proxy()
            copy = IndividualI()
            copy._id = self._id;
            copy._version = self._version;
            copy._details = None  # Unloading for the moment.
            raise omero.ClientError("NYI")
      def proxy(self, current = None):
          if self._id is None: raise omero.ClientError("Proxies require an id")
          return IndividualI( self._id.getValue(), False )

      def getDetails(self, current = None):
          self.errorIfUnloaded()
          return self._details

      def unloadDetails(self, current = None):
          self._details = None

      def getId(self, current = None):
          return self._id

      def setId(self, _id, current = None):
          self._id = _id

      def checkUnloadedProperty(self, value, loadedField):
          if value == None:
              self.__dict__[loadedField] = False
          else:
              self.__dict__[loadedField] = True

      def getVersion(self, current = None):
          self.errorIfUnloaded()
          return self._version

      def setVersion(self, version, current = None):
          self.errorIfUnloaded()
          self._version = version

      def unloadVid(self, ):
          self._vidLoaded = False
          self._vid = None;

      def getVid(self, current = None):
          self.errorIfUnloaded()
          return self._vid

      def setVid(self, _vid, current = None):
          self.errorIfUnloaded()
          self._vid = _vid
          pass

      def unloadGender(self, ):
          self._genderLoaded = False
          self._gender = None;

      def getGender(self, current = None):
          self.errorIfUnloaded()
          return self._gender

      def setGender(self, _gender, current = None):
          self.errorIfUnloaded()
          self._gender = _gender
          pass

      def unloadFather(self, ):
          self._fatherLoaded = False
          self._father = None;

      def getFather(self, current = None):
          self.errorIfUnloaded()
          return self._father

      def setFather(self, _father, current = None):
          self.errorIfUnloaded()
          self._father = _father
          pass

      def unloadFatherTrusted(self, ):
          self._fatherTrustedLoaded = False
          self._fatherTrusted = None;

      def getFatherTrusted(self, current = None):
          self.errorIfUnloaded()
          return self._fatherTrusted

      def setFatherTrusted(self, _fatherTrusted, current = None):
          self.errorIfUnloaded()
          self._fatherTrusted = _fatherTrusted
          pass

      def unloadMother(self, ):
          self._motherLoaded = False
          self._mother = None;

      def getMother(self, current = None):
          self.errorIfUnloaded()
          return self._mother

      def setMother(self, _mother, current = None):
          self.errorIfUnloaded()
          self._mother = _mother
          pass

      def unloadMotherTrusted(self, ):
          self._motherTrustedLoaded = False
          self._motherTrusted = None;

      def getMotherTrusted(self, current = None):
          self.errorIfUnloaded()
          return self._motherTrusted

      def setMotherTrusted(self, _motherTrusted, current = None):
          self.errorIfUnloaded()
          self._motherTrusted = _motherTrusted
          pass

      def unloadAction(self, ):
          self._actionLoaded = False
          self._action = None;

      def getAction(self, current = None):
          self.errorIfUnloaded()
          return self._action

      def setAction(self, _action, current = None):
          self.errorIfUnloaded()
          self._action = _action
          pass

      def unloadLastUpdate(self, ):
          self._lastUpdateLoaded = False
          self._lastUpdate = None;

      def getLastUpdate(self, current = None):
          self.errorIfUnloaded()
          return self._lastUpdate

      def setLastUpdate(self, _lastUpdate, current = None):
          self.errorIfUnloaded()
          self._lastUpdate = _lastUpdate
          pass


      def ice_postUnmarshal(self):
          """
          Provides additional initialization once all data loaded
          """
          pass # Currently unused


      def ice_preMarshal(self):
          """
          Provides additional validation before data is sent
          """
          pass # Currently unused

      def __getattr__(self, name):
          import __builtin__
          """
          Reroutes all access to object.field through object.getField() or object.isField()
          """
          field  = "_" + name
          capitalized = name[0].capitalize() + name[1:]
          getter = "get" + capitalized
          questn = "is" + capitalized
          try:
              self.__dict__[field]
              if hasattr(self, getter):
                  method = getattr(self, getter)
                  return method()
              elif hasattr(self, questn):
                  method = getattr(self, questn)
                  return method()
          except:
              pass
          raise AttributeError("'%s' object has no attribute '%s' or '%s'" % (self.__class__.__name__, getter, questn))

      def __setattr__(self, name, value):
          """
          Reroutes all access to object.field through object.getField(), with the caveat
          that all sets on variables starting with "_" are permitted directly.
          """
          if name.startswith("_"):
              self.__dict__[name] = value
              return
          else:
              field  = "_" + name
              setter = "set" + name[0].capitalize() + name[1:]
              if hasattr(self, field) and hasattr(self, setter):
                  method = getattr(self, setter)
                  return method(value)
          raise AttributeError("'%s' object has no attribute '%s'" % (self.__class__.__name__, setter))

_omero_model.IndividualI = IndividualI
