# **********************************************************************
#
# Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.4.2
#
# <auto-generated>
#
# Generated from file `SequencerOutput.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy, __builtin__
import omero_model_IObject_ice
import omero_RTypes_ice
import omero_System_ice
import omero_Collections_ice
import omero_model_DataSample_ice

# Included module omero
_M_omero = Ice.openModule('omero')

# Included module omero.model
_M_omero.model = Ice.openModule('omero.model')

# Included module Ice
_M_Ice = Ice.openModule('Ice')

# Included module omero.sys
_M_omero.sys = Ice.openModule('omero.sys')

# Included module omero.api
_M_omero.api = Ice.openModule('omero.api')

# Start of module omero
__name__ = 'omero'

# Start of module omero.model
__name__ = 'omero.model'

if not _M_omero.model.__dict__.has_key('DataSampleStatus'):
    _M_omero.model._t_DataSampleStatus = IcePy.declareClass('::omero::model::DataSampleStatus')
    _M_omero.model._t_DataSampleStatusPrx = IcePy.declareProxy('::omero::model::DataSampleStatus')

if not _M_omero.model.__dict__.has_key('Action'):
    _M_omero.model._t_Action = IcePy.declareClass('::omero::model::Action')
    _M_omero.model._t_ActionPrx = IcePy.declareProxy('::omero::model::Action')

if not _M_omero.model.__dict__.has_key('Details'):
    _M_omero.model._t_Details = IcePy.declareClass('::omero::model::Details')
    _M_omero.model._t_DetailsPrx = IcePy.declareProxy('::omero::model::Details')

if not _M_omero.model.__dict__.has_key('SequencerOutput'):
    _M_omero.model.SequencerOutput = Ice.createTempClass()
    class SequencerOutput(_M_omero.model.DataSample):
        def __init__(self, _id=None, _details=None, _loaded=False, _version=None, _vid=None, _label=None, _creationDate=None, _status=None, _action=None):
            if __builtin__.type(self) == _M_omero.model.SequencerOutput:
                raise RuntimeError('omero.model.SequencerOutput is an abstract class')
            _M_omero.model.DataSample.__init__(self, _id, _details, _loaded, _version, _vid, _label, _creationDate, _status, _action)

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::omero::model::DataSample', '::omero::model::IObject', '::omero::model::SequencerOutput')

        def ice_id(self, current=None):
            return '::omero::model::SequencerOutput'

        def ice_staticId():
            return '::omero::model::SequencerOutput'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_omero.model._t_SequencerOutput)

        __repr__ = __str__

    _M_omero.model.SequencerOutputPrx = Ice.createTempClass()
    class SequencerOutputPrx(_M_omero.model.DataSamplePrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_omero.model.SequencerOutputPrx.ice_checkedCast(proxy, '::omero::model::SequencerOutput', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_omero.model.SequencerOutputPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_omero.model._t_SequencerOutputPrx = IcePy.defineProxy('::omero::model::SequencerOutput', SequencerOutputPrx)

    _M_omero.model._t_SequencerOutput = IcePy.declareClass('::omero::model::SequencerOutput')

    _M_omero.model._t_SequencerOutput = IcePy.defineClass('::omero::model::SequencerOutput', SequencerOutput, (), True, _M_omero.model._t_DataSample, (), ())
    SequencerOutput._ice_type = _M_omero.model._t_SequencerOutput

    _M_omero.model.SequencerOutput = SequencerOutput
    del SequencerOutput

    _M_omero.model.SequencerOutputPrx = SequencerOutputPrx
    del SequencerOutputPrx

# End of module omero.model

__name__ = 'omero'

# End of module omero
