# **********************************************************************
#
# Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.4.2
#
# <auto-generated>
#
# Generated from file `Region.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy, __builtin__
import omero_model_IObject_ice
import omero_RTypes_ice
import omero_System_ice
import omero_Collections_ice
import omero_model_Location_ice

# Included module omero
_M_omero = Ice.openModule('omero')

# Included module omero.model
_M_omero.model = Ice.openModule('omero.model')

# Included module Ice
_M_Ice = Ice.openModule('Ice')

# Included module omero.sys
_M_omero.sys = Ice.openModule('omero.sys')

# Included module omero.api
_M_omero.api = Ice.openModule('omero.api')

# Start of module omero
__name__ = 'omero'

# Start of module omero.model
__name__ = 'omero.model'

if not _M_omero.model.__dict__.has_key('Details'):
    _M_omero.model._t_Details = IcePy.declareClass('::omero::model::Details')
    _M_omero.model._t_DetailsPrx = IcePy.declareProxy('::omero::model::Details')

if not _M_omero.model.__dict__.has_key('Region'):
    _M_omero.model.Region = Ice.createTempClass()
    class Region(_M_omero.model.Location):
        def __init__(self, _id=None, _details=None, _loaded=False, _version=None, _vid=None, _name=None, _istatCode=None, _lastUpdate=None, _ceaseDate=None):
            if __builtin__.type(self) == _M_omero.model.Region:
                raise RuntimeError('omero.model.Region is an abstract class')
            _M_omero.model.Location.__init__(self, _id, _details, _loaded, _version, _vid, _name, _istatCode, _lastUpdate, _ceaseDate)

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::omero::model::IObject', '::omero::model::Location', '::omero::model::Region')

        def ice_id(self, current=None):
            return '::omero::model::Region'

        def ice_staticId():
            return '::omero::model::Region'
        ice_staticId = staticmethod(ice_staticId)

        def __str__(self):
            return IcePy.stringify(self, _M_omero.model._t_Region)

        __repr__ = __str__

    _M_omero.model.RegionPrx = Ice.createTempClass()
    class RegionPrx(_M_omero.model.LocationPrx):

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_omero.model.RegionPrx.ice_checkedCast(proxy, '::omero::model::Region', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_omero.model.RegionPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_omero.model._t_RegionPrx = IcePy.defineProxy('::omero::model::Region', RegionPrx)

    _M_omero.model._t_Region = IcePy.declareClass('::omero::model::Region')

    _M_omero.model._t_Region = IcePy.defineClass('::omero::model::Region', Region, (), True, _M_omero.model._t_Location, (), ())
    Region._ice_type = _M_omero.model._t_Region

    _M_omero.model.Region = Region
    del Region

    _M_omero.model.RegionPrx = RegionPrx
    del RegionPrx

# End of module omero.model

__name__ = 'omero'

# End of module omero
