# **********************************************************************
#
# Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.4.2
#
# <auto-generated>
#
# Generated from file `RawSeqDataSample.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy, __builtin__
import omero_model_IObject_ice
import omero_RTypes_ice
import omero_System_ice
import omero_Collections_ice
import omero_model_DataSample_ice

# Included module omero
_M_omero = Ice.openModule('omero')

# Included module omero.model
_M_omero.model = Ice.openModule('omero.model')

# Included module Ice
_M_Ice = Ice.openModule('Ice')

# Included module omero.sys
_M_omero.sys = Ice.openModule('omero.sys')

# Included module omero.api
_M_omero.api = Ice.openModule('omero.api')

# Start of module omero
__name__ = 'omero'

# Start of module omero.model
__name__ = 'omero.model'

if not _M_omero.model.__dict__.has_key('Lane'):
    _M_omero.model._t_Lane = IcePy.declareClass('::omero::model::Lane')
    _M_omero.model._t_LanePrx = IcePy.declareProxy('::omero::model::Lane')

if not _M_omero.model.__dict__.has_key('DataSampleStatus'):
    _M_omero.model._t_DataSampleStatus = IcePy.declareClass('::omero::model::DataSampleStatus')
    _M_omero.model._t_DataSampleStatusPrx = IcePy.declareProxy('::omero::model::DataSampleStatus')

if not _M_omero.model.__dict__.has_key('Action'):
    _M_omero.model._t_Action = IcePy.declareClass('::omero::model::Action')
    _M_omero.model._t_ActionPrx = IcePy.declareProxy('::omero::model::Action')

if not _M_omero.model.__dict__.has_key('Details'):
    _M_omero.model._t_Details = IcePy.declareClass('::omero::model::Details')
    _M_omero.model._t_DetailsPrx = IcePy.declareProxy('::omero::model::Details')

if not _M_omero.model.__dict__.has_key('RawSeqDataSample'):
    _M_omero.model.RawSeqDataSample = Ice.createTempClass()
    class RawSeqDataSample(_M_omero.model.DataSample):
        def __init__(self, _id=None, _details=None, _loaded=False, _version=None, _vid=None, _label=None, _creationDate=None, _status=None, _action=None, _lane=None):
            if __builtin__.type(self) == _M_omero.model.RawSeqDataSample:
                raise RuntimeError('omero.model.RawSeqDataSample is an abstract class')
            _M_omero.model.DataSample.__init__(self, _id, _details, _loaded, _version, _vid, _label, _creationDate, _status, _action)
            self._lane = _lane

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::omero::model::DataSample', '::omero::model::IObject', '::omero::model::RawSeqDataSample')

        def ice_id(self, current=None):
            return '::omero::model::RawSeqDataSample'

        def ice_staticId():
            return '::omero::model::RawSeqDataSample'
        ice_staticId = staticmethod(ice_staticId)

        def getLane(self, current=None):
            pass

        def setLane(self, theLane, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_omero.model._t_RawSeqDataSample)

        __repr__ = __str__

    _M_omero.model.RawSeqDataSamplePrx = Ice.createTempClass()
    class RawSeqDataSamplePrx(_M_omero.model.DataSamplePrx):

        def getLane(self, _ctx=None):
            return _M_omero.model.RawSeqDataSample._op_getLane.invoke(self, ((), _ctx))

        def begin_getLane(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.RawSeqDataSample._op_getLane.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getLane(self, _r):
            return _M_omero.model.RawSeqDataSample._op_getLane.end(self, _r)

        def setLane(self, theLane, _ctx=None):
            return _M_omero.model.RawSeqDataSample._op_setLane.invoke(self, ((theLane, ), _ctx))

        def begin_setLane(self, theLane, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.model.RawSeqDataSample._op_setLane.begin(self, ((theLane, ), _response, _ex, _sent, _ctx))

        def end_setLane(self, _r):
            return _M_omero.model.RawSeqDataSample._op_setLane.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_omero.model.RawSeqDataSamplePrx.ice_checkedCast(proxy, '::omero::model::RawSeqDataSample', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_omero.model.RawSeqDataSamplePrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_omero.model._t_RawSeqDataSamplePrx = IcePy.defineProxy('::omero::model::RawSeqDataSample', RawSeqDataSamplePrx)

    _M_omero.model._t_RawSeqDataSample = IcePy.declareClass('::omero::model::RawSeqDataSample')

    _M_omero.model._t_RawSeqDataSample = IcePy.defineClass('::omero::model::RawSeqDataSample', RawSeqDataSample, (), True, _M_omero.model._t_DataSample, (), (('_lane', (), _M_omero.model._t_Lane),))
    RawSeqDataSample._ice_type = _M_omero.model._t_RawSeqDataSample

    RawSeqDataSample._op_getLane = IcePy.Operation('getLane', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), _M_omero.model._t_Lane, ())
    RawSeqDataSample._op_setLane = IcePy.Operation('setLane', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), _M_omero.model._t_Lane),), (), None, ())

    _M_omero.model.RawSeqDataSample = RawSeqDataSample
    del RawSeqDataSample

    _M_omero.model.RawSeqDataSamplePrx = RawSeqDataSamplePrx
    del RawSeqDataSamplePrx

# End of module omero.model

__name__ = 'omero'

# End of module omero
