"""
   /*
   **   Generated by blitz/templates/resouces/combined.vm
   **
   **   Copyright 2007, 2008 Glencoe Software, Inc. All rights reserved.
   **   Use is subject to license terms supplied in LICENSE.txt
   **
   */
"""
import Ice
import IceImport
import omero
IceImport.load("omero_model_DetailsI")
IceImport.load("omero_model_IlluminaBeadChipMeasures_ice")
from omero.rtypes import rlong
_omero = Ice.openModule("omero")
_omero_model = Ice.openModule("omero.model")
__name__ = "omero.model"
class IlluminaBeadChipMeasuresI(_omero_model.IlluminaBeadChipMeasures):

      REDCHANNEL =  "ome.model.vl.IlluminaBeadChipMeasures_redChannel"
      GREENCHANNEL =  "ome.model.vl.IlluminaBeadChipMeasures_greenChannel"
      VID =  "ome.model.vl.IlluminaBeadChipMeasures_vid"
      LABEL =  "ome.model.vl.IlluminaBeadChipMeasures_label"
      CREATIONDATE =  "ome.model.vl.IlluminaBeadChipMeasures_creationDate"
      ACTION =  "ome.model.vl.IlluminaBeadChipMeasures_action"
      LASTUPDATE =  "ome.model.vl.IlluminaBeadChipMeasures_lastUpdate"
      DETAILS =  "ome.model.vl.IlluminaBeadChipMeasures_details"
      def errorIfUnloaded(self):
          if not self._loaded:
              raise _omero.UnloadedEntityException("Object unloaded:"+str(self))

      def throwNullCollectionException(self,propertyName):
          raise _omero.UnloadedEntityException(""+
          "Error updating collection:" + propertyName +"\n"+
          "Collection is currently null. This can be seen\n" +
          "by testing \""+ propertyName +"Loaded\". This implies\n"+
          "that this collection was unloaded. Please refresh this object\n"+
          "in order to update this collection.\n")

      def _toggleCollectionsLoaded(self,load):
          pass

      def __init__(self, id = None, loaded = True):
          super(IlluminaBeadChipMeasuresI, self).__init__()
          # Relying on omero.rtypes.rlong's error-handling
          self._id = rlong(id)
          self._loaded = loaded
          if self._loaded:
             self._details = _omero_model.DetailsI()
             self._toggleCollectionsLoaded(True)

      def unload(self, current = None):
          self._loaded = False
          self.unloadRedChannel( )
          self.unloadGreenChannel( )
          self.unloadVid( )
          self.unloadLabel( )
          self.unloadCreationDate( )
          self.unloadAction( )
          self.unloadLastUpdate( )
          self.unloadDetails( )

      def isLoaded(self, current = None):
          return self._loaded
      def unloadCollections(self, current = None):
          self._toggleCollectionsLoaded( False )
      def isGlobal(self, current = None):
          return  False ;
      def isMutable(self, current = None):
          return  True ;
      def isAnnotated(self, current = None):
          return  False ;
      def isLink(self, current = None):
          return  False ;
      def shallowCopy(self, current = None):
            if not self._loaded: return self.proxy()
            copy = IlluminaBeadChipMeasuresI()
            copy._id = self._id;
            copy._version = self._version;
            copy._details = None  # Unloading for the moment.
            raise omero.ClientError("NYI")
      def proxy(self, current = None):
          if self._id is None: raise omero.ClientError("Proxies require an id")
          return IlluminaBeadChipMeasuresI( self._id.getValue(), False )

      def getDetails(self, current = None):
          self.errorIfUnloaded()
          return self._details

      def unloadDetails(self, current = None):
          self._details = None

      def getId(self, current = None):
          return self._id

      def setId(self, _id, current = None):
          self._id = _id

      def checkUnloadedProperty(self, value, loadedField):
          if value == None:
              self.__dict__[loadedField] = False
          else:
              self.__dict__[loadedField] = True

      def getVersion(self, current = None):
          self.errorIfUnloaded()
          return self._version

      def setVersion(self, version, current = None):
          self.errorIfUnloaded()
          self._version = version

      def unloadRedChannel(self, ):
          self._redChannelLoaded = False
          self._redChannel = None;

      def getRedChannel(self, current = None):
          self.errorIfUnloaded()
          return self._redChannel

      def setRedChannel(self, _redChannel, current = None):
          self.errorIfUnloaded()
          self._redChannel = _redChannel
          pass

      def unloadGreenChannel(self, ):
          self._greenChannelLoaded = False
          self._greenChannel = None;

      def getGreenChannel(self, current = None):
          self.errorIfUnloaded()
          return self._greenChannel

      def setGreenChannel(self, _greenChannel, current = None):
          self.errorIfUnloaded()
          self._greenChannel = _greenChannel
          pass

      def unloadVid(self, ):
          self._vidLoaded = False
          self._vid = None;

      def getVid(self, current = None):
          self.errorIfUnloaded()
          return self._vid

      def setVid(self, _vid, current = None):
          self.errorIfUnloaded()
          self._vid = _vid
          pass

      def unloadLabel(self, ):
          self._labelLoaded = False
          self._label = None;

      def getLabel(self, current = None):
          self.errorIfUnloaded()
          return self._label

      def setLabel(self, _label, current = None):
          self.errorIfUnloaded()
          self._label = _label
          pass

      def unloadCreationDate(self, ):
          self._creationDateLoaded = False
          self._creationDate = None;

      def getCreationDate(self, current = None):
          self.errorIfUnloaded()
          return self._creationDate

      def setCreationDate(self, _creationDate, current = None):
          self.errorIfUnloaded()
          self._creationDate = _creationDate
          pass

      def unloadAction(self, ):
          self._actionLoaded = False
          self._action = None;

      def getAction(self, current = None):
          self.errorIfUnloaded()
          return self._action

      def setAction(self, _action, current = None):
          self.errorIfUnloaded()
          self._action = _action
          pass

      def unloadLastUpdate(self, ):
          self._lastUpdateLoaded = False
          self._lastUpdate = None;

      def getLastUpdate(self, current = None):
          self.errorIfUnloaded()
          return self._lastUpdate

      def setLastUpdate(self, _lastUpdate, current = None):
          self.errorIfUnloaded()
          self._lastUpdate = _lastUpdate
          pass


      def ice_postUnmarshal(self):
          """
          Provides additional initialization once all data loaded
          """
          pass # Currently unused


      def ice_preMarshal(self):
          """
          Provides additional validation before data is sent
          """
          pass # Currently unused

      def __getattr__(self, name):
          import __builtin__
          """
          Reroutes all access to object.field through object.getField() or object.isField()
          """
          field  = "_" + name
          capitalized = name[0].capitalize() + name[1:]
          getter = "get" + capitalized
          questn = "is" + capitalized
          try:
              self.__dict__[field]
              if hasattr(self, getter):
                  method = getattr(self, getter)
                  return method()
              elif hasattr(self, questn):
                  method = getattr(self, questn)
                  return method()
          except:
              pass
          raise AttributeError("'%s' object has no attribute '%s' or '%s'" % (self.__class__.__name__, getter, questn))

      def __setattr__(self, name, value):
          """
          Reroutes all access to object.field through object.getField(), with the caveat
          that all sets on variables starting with "_" are permitted directly.
          """
          if name.startswith("_"):
              self.__dict__[name] = value
              return
          else:
              field  = "_" + name
              setter = "set" + name[0].capitalize() + name[1:]
              if hasattr(self, field) and hasattr(self, setter):
                  method = getattr(self, setter)
                  return method(value)
          raise AttributeError("'%s' object has no attribute '%s'" % (self.__class__.__name__, setter))

_omero_model.IlluminaBeadChipMeasuresI = IlluminaBeadChipMeasuresI
